import type { NextPage } from 'next';
import Head from 'next/head';

import styles from '../styles/Home.module.scss';
import Losses from 'containers/Losses';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <video autoPlay muted loop>
          <source
            src="/video/background/fog_background.webm"
            type="video/webm"
          />
          <source src="/video/background/fog_background.mp4" type="video/mp4" />
        </video>
        <Losses />
      </main>
    </div>
  );
};

export default Home;
