import { useState } from 'react';

import type { NextPage } from 'next';
import Head from 'next/head';
// import { useTranslation } from 'react-i18next';

import LocaleSwitch from 'components/LocaleSwitch';
import Header from 'containers/Header';
import Losses from 'containers/Losses';

import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  const [locale, setLocale] = useState<string>('uk');

  return (
    <div className={styles.container}>
      <Head>
        <title>Втрати окупантів</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <video autoPlay muted loop>
          <source
            src="/video/background/fog_background.webm"
            type="video/webm"
          />
          <source src="/video/background/fog_background.mp4" type="video/mp4" />
        </video>
        <LocaleSwitch changeLanguage={(value: string) => setLocale(value)} />
        <div>
          <Header locale={locale} />
          <Losses locale={locale} />
        </div>
      </main>
    </div>
  );
};

export default Home;
